name: DNN-based_source_separation_wham-cpu

channels:
  - pytorch
  - defaults
  - conda-forge

dependencies:
  - python>=3.6,<=3.8
  - numpy>=1.19
  - matplotlib>=3.3.2
  - mir_eval==0.6
  - pytorch>=1.8.0
  - torchaudio>=0.8.0